<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Domain\Entities\" />
      <Folder Include="Domain\RepositoryContracts\" />
      <Folder Include="Enums\" />
      <Folder Include="Exceptions\" />
      <Folder Include="Helpers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ConverterWebsite.Infastructure\ConverterWebsite.Infastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    </ItemGroup>

</Project>
